version: "3"
services:
  server:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db
      - client
    environment:
      DATABASE_URL: "postgresql://postgres:123456@db:5432/f1nderas?schema=public"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres # Имя пользователя PostgreSQL
      POSTGRES_PASSWORD: 123456 # Пароль пользователя
      POSTGRES_DB: f1nderas # Название базы данных
  client:
    build: ../client-side
    ports:
      - "3000:3000"
